[versions]
# libraries
junit = "4.13.2"

# plugins
intelliJPlatform = "2.5.0"
kotlin = "2.1.20"
ktlint = "12.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
