name: Java CI

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref origin/${{ github.event.pull_request.base.ref }} --to-ref HEAD

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: check buildPlugin
